var pool = require('../../db/pool');

var sql = {}; // 保存sql语句
/***********首页工作排名(全程健康)***********/
sql['/api/home/jobranking'] = {
    realtime: false,
    pool: pool.btdPool,
    sql: {
        countyData: "select county, "
        + " SUM(CASE WHEN flag='sjbb' THEN cnt ELSE 0 END ) sfbb_cnt,"
        + " SUM(CASE WHEN flag='swm' THEN cnt ELSE 0 END ) swm_cnt"
        + " from "
        + " ("
        + " select "
        + " flag,"
        + " IF(dic_county.county IS NULL,'其它',dic_county.county) county,"
        + " hospital_info.hospital_name,"
        + " count(distinct zfx_report.hospital_id ,personcard_no) cnt "
        + " from "
        + " ("
        + " select distinct screen_hospital  hospital_id,  personcard_no, 'sjbb' as flag from "
        + " dash_g_dp_bfz_tw_filter  filter"
        + " inner JOIN"
        + " dash_g_dp_bfz_tw_sjbb sjbb"
        + " ON filter.exam_id=sjbb.examoid"
        + " and sjbb.dry_left is not null"
        + " union ALL"
        + " select distinct screen_hospital hospital_id ,  personcard_no, 'swm' as flag from "
        + " dash_g_dp_bfz_tw_filter  filter"
        + " inner JOIN"
        + " dash_g_dp_bfz_tw_swm swm"
        + " ON  filter.exam_id=swm.examoid and swm.diag_diab_yes_right is not null"
        + " ) zfx_report "
        + " right JOIN dash_g_t_dic_hospital_info hospital_info on zfx_report.hospital_id=hospital_info.hospital_id"
        + " and zfx_report.personcard_no is not null and zfx_report.hospital_id is not null"
        + " LEFT JOIN (SELECT code,IF(substr(code,1,3)='310',explain_memo,'其它') as county FROM hc_t_dic_area WHERE level='3') dic_county on hospital_info.address_county=dic_county.code"
        + " group by  IF(dic_county.county IS NULL,'其它',dic_county.county),zfx_report.hospital_id,hospital_info.hospital_name,flag"
        + " ) source "
        + " GROUP BY county",
        hospitalData: "select county,hospital_name ,sfbb_cnt,swm_cnt,hospital_type from"
        + " ("
        + " select county,hospital_name ,hospital_type,"
        + " SUM(CASE WHEN flag='sjbb' THEN cnt ELSE 0 END ) sfbb_cnt,"
        + " SUM(CASE WHEN flag='swm' THEN cnt ELSE 0 END ) swm_cnt"
        + " from "
        + " ("
        + " select "
        + " flag,"
        + " IF(dic_county.county IS NULL,'其它',dic_county.county) county,"
        + " hospital_info.hospital_name,"
        + " hospital_info.hospital_type,"
        + " count(distinct zfx_report.hospital_id ,personcard_no) cnt "
        + " from "
        + " ("
        + " select distinct screen_hospital  hospital_id,  personcard_no, 'sjbb' as flag from "
        + " dash_g_dp_bfz_tw_filter  filter"
        + " inner JOIN"
        + " dash_g_dp_bfz_tw_sjbb sjbb"
        + " ON filter.exam_id=sjbb.examoid"
        + " and sjbb.dry_left is not null"
        + " union ALL"
        + " select distinct screen_hospital hospital_id ,  personcard_no, 'swm' as flag from "
        + " dash_g_dp_bfz_tw_filter  filter"
        + " inner JOIN"
        + " dash_g_dp_bfz_tw_swm swm"
        + " ON  filter.exam_id=swm.examoid and swm.diag_diab_yes_right is not null"
        + " ) zfx_report "
        + " right JOIN dash_g_t_dic_hospital_info hospital_info on zfx_report.hospital_id=hospital_info.hospital_id"
        + " and zfx_report.personcard_no is not null and zfx_report.hospital_id is not null"
        + " LEFT JOIN (SELECT code,IF(substr(code,1,3)='310',explain_memo,'其它') as county FROM hc_t_dic_area WHERE level='3') dic_county on hospital_info.address_county=dic_county.code"
        + " group by  IF(dic_county.county IS NULL,'其它',dic_county.county),zfx_report.hospital_id,hospital_info.hospital_name,flag,hospital_info.hospital_type"
        + " ) source "
        + " GROUP BY county,hospital_name,hospital_type"
        + " )t"
        + " where  not  ( hospital_type <> 'B1'  and sfbb_cnt+swm_cnt=0)"
    }
}
/***********首页情况分析(全程健康)***********/
sql['/api/home/analysis'] = {
    realtime: false,
    pool: pool.btdPool,
    sql: {
        countyData: "select county," //各区县数据
        +" qb_cnt,"
        +" sjbb_cnt,"
        +" qb_cnt-sjbb_cnt  sjbb_uncom,"
        +" swm_cnt ,"
        +" qb_cnt-swm_cnt swm_uncom ,"
        +" both_cnt ,"
        +" none_cnt,"
        +" case when qb_cnt =0 then 0 else sjbb_cnt/qb_cnt end as sjbb_rate ,"
        +" case when qb_cnt =0 then 0 else (qb_cnt-sjbb_cnt)/qb_cnt end as sjbb_uncom_rate,"
        +" case when qb_cnt =0 then 0 else swm_cnt/qb_cnt end as swm_rate ,"
        +" case when qb_cnt =0 then 0 else (qb_cnt-swm_cnt)/qb_cnt end as swm_uncom_rate ,"
        +" case when qb_cnt =0 then 0 else both_cnt/qb_cnt end as both_rate ,"
        +" case when qb_cnt =0 then 0 else none_cnt/qb_cnt end as none_rate"
        +" FROM"
        +" ("
        +" select county,"
        +" SUM(CASE WHEN flag='qb' THEN cnt ELSE 0 END ) qb_cnt,"
        +" SUM(CASE WHEN flag in ('sjbb','both') THEN cnt ELSE 0 END ) sjbb_cnt,"
        +" SUM(CASE WHEN flag in ('swm','both') THEN cnt ELSE 0 END ) swm_cnt,"
        +" SUM(CASE WHEN flag ='both' THEN cnt ELSE 0 END ) both_cnt,"
        +" SUM(CASE WHEN flag ='none' THEN cnt ELSE 0 END ) none_cnt"
        +" from "
        +" ("
        +" select "
        +" flag,"
        +" IF(dic_county.county IS NULL,'其它',dic_county.county) county,"
        +" hospital_info.hospital_name,"
        +" count(distinct zfx_report.hospital_id ,personcard_no) cnt "
        +" from "
        +" ("
        +" select   distinct hospital_id,personcard_no,"
        +" case when"
        +" sjbb_examoid IS not  NULL and swm_examoid IS not  NULL then 'both' "
        +" when sjbb_examoid IS not  NULL and swm_examoid IS   NULL then 'sjbb'"
        +" when sjbb_examoid IS   NULL and swm_examoid IS  not  NULL then 'swm'"
        +" else 'none'"
        +" end as flag from"
        +" ("
        +" select distinct screen_hospital  hospital_id,  personcard_no,sjbb.examoid sjbb_examoid,swm.examoid swm_examoid"
        +" from"
        +" dash_g_dp_bfz_tw_filter  filter"
        +" left JOIN"
        +" dash_g_dp_bfz_tw_sjbb sjbb"
        +" ON filter.exam_id=sjbb.examoid"
        +" and sjbb.dry_left is not null"
        +" left JOIN"
        +" dash_g_dp_bfz_tw_swm swm"
        +" ON  filter.exam_id=swm.examoid and swm.diag_diab_yes_right is not null"
        +" ) t"
        +" union all"
        +" select distinct screen_hospital hospital_id ,  personcard_no, 'qb' as flag from "
        +" dash_g_dp_bfz_tw_filter  filter"
        +" ) zfx_report "
        +" right JOIN dash_g_t_dic_hospital_info hospital_info on zfx_report.hospital_id=hospital_info.hospital_id"
        +" and zfx_report.personcard_no is not null and zfx_report.hospital_id is not null"
        +" LEFT JOIN (SELECT code,IF(substr(code,1,3)='310',explain_memo,'其它') as county FROM hc_t_dic_area WHERE level='3') dic_county on hospital_info.address_county=dic_county.code"
        +" group by  IF(dic_county.county IS NULL,'其它',dic_county.county),zfx_report.hospital_id,hospital_info.hospital_name,flag"
        +" ) source "
        +" GROUP BY county"
        +" )t",
        screeningPopulation:"select count(distinct personcard_no) from dash_g_dp_bfz_tw_filter  filter", //参加筛查总人数
        cityData:"select "
        +" qb_cnt,"
        +" sjbb_cnt, "
        +" qb_cnt-sjbb_cnt  sjbb_uncom,"
        +" swm_cnt , "
        +" qb_cnt-swm_cnt swm_uncom ,"
        +" both_cnt ,"
        +" none_cnt, "
        +" case when qb_cnt =0 then 0 else sjbb_cnt/qb_cnt end as sjbb_rate ,"
        +" case when qb_cnt =0 then 0 else (qb_cnt-sjbb_cnt)/qb_cnt end as sjbb_uncom_rate, "
        +" case when qb_cnt =0 then 0 else swm_cnt/qb_cnt end as swm_rate ,"
        +" case when qb_cnt =0 then 0 else (qb_cnt-swm_cnt)/qb_cnt end as swm_uncom_rate ,"
        +" case when qb_cnt =0 then 0 else both_cnt/qb_cnt end as both_rate ,"
        +" case when qb_cnt =0 then 0 else none_cnt/qb_cnt end as none_rate"
        +" from"
        +" ("
        +" select "
        +" count(distinct CASE WHEN flag='qb' THEN concat( personcard_no,hospital_id) ELSE null END ) qb_cnt,"
        +" count(distinct CASE WHEN flag in ('sjbb','both') THEN concat( personcard_no,hospital_id) ELSE null END ) sjbb_cnt,"
        +" count(distinct CASE WHEN flag in ('swm','both') THEN concat( personcard_no,hospital_id) ELSE null  END ) swm_cnt,"
        +" count(distinct CASE WHEN flag ='both' THEN concat( personcard_no,hospital_id) ELSE null END ) both_cnt,"
        +" count(distinct CASE WHEN flag ='none' THEN concat( personcard_no,hospital_id) ELSE null  END ) none_cnt"
        +" from"
        +" ("
        +" select   distinct hospital_id,personcard_no,"
        +" case when"
        +" sjbb_examoid IS not  NULL and swm_examoid IS not  NULL then 'both' "
        +" when sjbb_examoid IS not  NULL and swm_examoid IS   NULL then 'sjbb'"
        +" when sjbb_examoid IS   NULL and swm_examoid IS  not  NULL then 'swm'"
        +" else 'none'"
        +" end as flag from"
        +" ("
        +" select distinct screen_hospital  hospital_id,  personcard_no,sjbb.examoid sjbb_examoid,swm.examoid swm_examoid"
        +" from"
        +" dash_g_dp_bfz_tw_filter  filter"
        +" left JOIN"
        +" dash_g_dp_bfz_tw_sjbb sjbb"
        +" ON filter.exam_id=sjbb.examoid"
        +" and sjbb.dry_left is not null"
        +" left JOIN"
        +" dash_g_dp_bfz_tw_swm swm"
        +" ON  filter.exam_id=swm.examoid and swm.diag_diab_yes_right is not null"
        +" ) t"
        +" union all"
        +" select distinct screen_hospital hospital_id ,  personcard_no, 'qb' as flag from "
        +" dash_g_dp_bfz_tw_filter  filter"
        +" )t"
        +" )t"
    }
}

sql['/api/result/analysis'] = {
    realtime: false,
    pool: pool.btdPool,
    sql: {
        retina: "SELECT IFNULL(county,'上海市') as county"
        +" ,COUNT(per_card) AS per_cnt  "
        +" ,COUNT(DISTINCT IF(eye_flag=0,per_card,NULL)) AS  per_cnt_normal "
        +" ,ROUND(COUNT(DISTINCT IF(eye_flag=0,per_card,NULL))/COUNT(per_card),3) AS per_cnt_normal_rate  "
        +" ,COUNT(DISTINCT IF(eye_flag=1,per_card,NULL)) AS  per_cnt_low "
        +" ,ROUND(COUNT(DISTINCT IF(eye_flag=1,per_card,NULL))/COUNT(per_card),3) AS per_cnt_low_rate  "
        +" ,COUNT(DISTINCT IF(eye_flag=2,per_card,NULL)) AS  per_cnt_mid "
        +" ,ROUND(COUNT(DISTINCT IF(eye_flag=2,per_card,NULL))/COUNT(per_card),3) AS per_cnt_mid_rate  "
        +" ,COUNT(DISTINCT IF(eye_flag=3,per_card,NULL)) AS  per_cnt_high "
        +" ,ROUND(COUNT(DISTINCT IF(eye_flag=3,per_card,NULL))/COUNT(per_card),3) AS per_cnt_high_rate "
        +" ,COUNT(DISTINCT IF(eye_flag=4,per_card,NULL)) AS  per_cnt_stage "
        +" ,ROUND(COUNT(DISTINCT IF(eye_flag=4,per_card,NULL))/COUNT(per_card),3) AS per_cnt_stage_rate  "
        +" FROM "
        +" (SELECT  per_card,county, IF(@per_no=xxx.per_card,@rank:=@rank+1,@rank:=1) AS rank,@per_no:=xxx.per_card,eye_flag"
        +"   FROM "
        +"   ("
        +"     SELECT  per_card,county,examoid,exam_date,eye_flag"
        +"     FROM"
        +"     (SELECT   CONCAT_WS(',',fillter.personcard_no,fillter.screen_hospital) AS per_card,dic.explain_memo as county,swm.examoid,swm.exam_date,swm.eye_flag"
        +"      FROM dash_g_dp_bfz_tw_filter  fillter"
        +"      JOIN(SELECT examoid, eyegroundexamtime exam_date"
        +"         ,IF(CASE WHEN diag_diab_yes_right='2'THEN '0'  WHEN diag_diab_stage_right='2'  THEN '4'WHEN diag_diab_degree_right='1' THEN '1'  WHEN diag_diab_degree_right='2' THEN '2'  WHEN diag_diab_degree_right='3' THEN '3' ELSE '99' END  "
        +"              > CASE  WHEN diag_diab_yes_left='2'THEN '0'   WHEN diag_diab_stage_left='2'   THEN '4'WHEN diag_diab_degree_left='1'  THEN '1' WHEN diag_diab_degree_left='2' THEN '2'  WHEN diag_diab_degree_left='3' THEN '3' ELSE '99' END "
        +"            ,CASE WHEN diag_diab_yes_right='2'THEN '0'  WHEN diag_diab_stage_right='2'  THEN '4'WHEN diag_diab_degree_right='1' THEN '1'  WHEN diag_diab_degree_right='2' THEN '2'  WHEN diag_diab_degree_right='3' THEN '3' ELSE '99' END   "
        +"            ,CASE  WHEN diag_diab_yes_left='2'THEN '0'   WHEN diag_diab_stage_left='2'   THEN '4'WHEN diag_diab_degree_left='1'  THEN '1' WHEN diag_diab_degree_left='2' THEN '2'  WHEN diag_diab_degree_left='3' THEN '3' ELSE '99' END  ) AS eye_flag"
        +"            FROM dash_g_dp_bfz_tw_swm WHERE (diag_diab_yes_right IS NOT NULL  OR diag_diab_yes_left IS NOT NULL  )"
        +"           ) swm "
        +"     ON fillter.exam_id=swm.examoid"
        +"     LEFT JOIN (SELECT  hp_info.hospital_id,area.explain_memo,area.firstping"
        +"                 FROM dash_g_t_dic_hospital_info hp_info"
        +"                 LEFT JOIN (SELECT  code,explain_memo,firstping  FROM hc_t_dic_area WHERE  LEFT (code,3)='310' AND level='3') area"
        +"                ON hp_info.address_county=area.code"
        +"                ) dic"
        +"     ON fillter.screen_hospital=dic.hospital_id"
        +"     ) xx ORDER BY per_card,exam_date DESC"
        +"    )xxx,(SELECT  @per_no := null ,@rank:=0) r "
        +" ) tt where tt.rank=1"
        +" GROUP BY county WITH ROLLUP",
        nerve: "SELECT IFNULL(county,'上海市') as county"
        +" ,COUNT(per_card) AS per_cnt  "
        +" ,COUNT(DISTINCT IF(flag=1,per_card,NULL)) AS  per_cnt_low "
        +" ,ROUND(COUNT(DISTINCT IF(flag=1,per_card,NULL))/COUNT(per_card),3) AS per_cnt_low_rate  "
        +" ,COUNT(DISTINCT IF(flag=2,per_card,NULL)) AS  per_cnt_mid "
        +" ,ROUND(COUNT(DISTINCT IF(flag=2,per_card,NULL))/COUNT(per_card),3) AS per_cnt_mid_rate  "
        +" ,COUNT(DISTINCT IF(flag=3,per_card,NULL)) AS  per_cnt_high "
        +" ,ROUND(COUNT(DISTINCT IF(flag=3,per_card,NULL))/COUNT(per_card),3) AS per_cnt_high_rate  "
        +" FROM "
        +" ("
        +"   SELECT  per_card,county, IF(@per_no=xxx.per_card,@rank:=@rank+1,@rank:=1) AS rank,@per_no:=xxx.per_card,flag"
        +"   FROM "
        +"   ("
        +"     SELECT  per_card,county,examoid,vaexamtime,flag"
        +"     FROM"
        +"     ("
        +"     SELECT   CONCAT_WS(',',fillter.personcard_no,fillter.screen_hospital) AS per_card,dic.explain_memo as county,sjbb.examoid,sjbb.vaexamtime,sjbb.flag"
        +"     FROM dash_g_dp_bfz_tw_filter  fillter"
        +"     JOIN("
        +"        SELECT  examoid,vaexamtime,foot_count,IF(foot_count>=6,3,IF(foot_count BETWEEN 4 AND 5,2,1)) flag "
        +"        FROM"
        +"        ("
        +"        SELECT  x.examoid,x.vaexamtime"
        +"        ,(IF(sum(dry_left + chap_left + desquamation_left + corn_left + deformity_left + pallus_left + infection_left)>= 1,1,sum(dry_left + chap_left + desquamation_left + corn_left + deformity_left + pallus_left + infection_left))"
        +"        + sum(nelon_left + ulcer_left + vibra_left)"
        +"        +IF(sum(dry_right + chap_right + desquamation_right + corn_right + deformity_right + pallus_right + infection_right)>= 1,1,sum(dry_right + chap_right + desquamation_right + corn_right + deformity_right + pallus_right + infection_right))"
        +"        + sum(nelon_right + vibra_right + ulcer_right)"
        +"        ) as foot_count"
        +"        FROM"
        +"        ("
        +"        SELECT "
        +"        examoid"
        +"        ,vaexamtime"
        +"        ,CASE WHEN dry_left = '2' THEN 0 WHEN dry_left = '1' THEN 0.5 ELSE 0 END  as dry_left "
        +"        ,CASE WHEN chap_left = '2' THEN 0 WHEN chap_left = '1' THEN 0.5 ELSE 0 END  as chap_left "
        +"        ,CASE WHEN desquamation_left = '2' THEN 0 WHEN desquamation_left = '1' THEN 0.5 ELSE 0 END as desquamation_left "
        +"        ,CASE WHEN corn_left = '2' THEN 0 WHEN corn_left = '1' THEN 1 ELSE 0 END as corn_left "
        +"        ,CASE WHEN deformity_left = '1' THEN 0 WHEN deformity_left IN('2','3','4','5') THEN 1 ELSE 0 END as deformity_left "
        +"        ,CASE WHEN pallus_left = '1' THEN 0 WHEN pallus_left IN('2','3','4') THEN 0.5 ELSE 0 END as pallus_left "
        +"        ,CASE WHEN infection_left = '2' THEN 	0 WHEN infection_left = '1' THEN 0.5 ELSE 0 END as infection_left 	"
        +"        ,CASE WHEN ulcer_left = '2' THEN 0 WHEN ulcer_left = '1' THEN 1 ELSE 0 END as ulcer_left "
        +"        ,CASE WHEN nelon_left = '1' THEN 0 WHEN nelon_left = '2' THEN 0.5 WHEN nelon_left = '3' THEN 1 ELSE 0 END as nelon_left	"
        +"        ,CASE WHEN vibra_left = '1' THEN 0 WHEN vibra_left = '2' THEN 0.5 WHEN vibra_left = '3' THEN 1 ELSE 0 END as vibra_left "
        +"        ,CASE WHEN dry_right = '2' THEN 0 WHEN dry_right = '1' THEN 0.5 ELSE 0 END as dry_right"
        +"        ,CASE WHEN chap_right = '2' THEN 0 WHEN chap_right = '1' THEN 0.5 ELSE 0 END as chap_right"
        +"        ,CASE WHEN desquamation_right = '2' THEN 0 WHEN desquamation_right = '1' THEN 0.5 ELSE 0 END as desquamation_right"
        +"        ,CASE WHEN corn_right = '2' THEN 0 WHEN corn_right = '1' THEN 1 ELSE 0 END as corn_right"
        +"        ,CASE WHEN deformity_right = '1' THEN 0 WHEN deformity_right IN('2','3','4','5') THEN 1 ELSE 0 END as deformity_right"
        +"        ,CASE WHEN pallus_right = '1' THEN 0.5 WHEN pallus_right IN('2','3','4') THEN 0 ELSE 0 END as pallus_right"
        +"        ,CASE WHEN infection_right = '2' THEN 0 WHEN infection_right = '1' THEN 0.5 ELSE 0 END as infection_right"
        +"        ,CASE WHEN ulcer_right = '2' THEN 0 WHEN ulcer_right = '1' THEN 1 ELSE 0 END as ulcer_right"
        +"        ,CASE WHEN nelon_right = '1' THEN 0 WHEN nelon_right = '2' THEN 0.5 WHEN nelon_right = '3' THEN 1 ELSE 0 END as nelon_right"
        +"        ,CASE WHEN vibra_right = '1' THEN 0 WHEN vibra_right = '2' THEN 0.5 WHEN vibra_right = '3' THEN 1 ELSE 0 END as vibra_right"
        +"        FROM dash_g_dp_bfz_tw_sjbb "
        +"        WHERE  (dry_left IS NOT NULL OR  chap_left IS NOT NULL OR  desquamation_left IS NOT NULL OR  corn_left IS NOT NULL OR  deformity_left IS NOT NULL "
        +"        OR  pallus_left IS NOT NULL OR  infection_left IS NOT NULL OR nelon_left IS NOT NULL OR  ulcer_left IS NOT NULL OR  vibra_left  IS NOT NULL "
        +"        OR dry_right IS NOT NULL OR  chap_right IS NOT NULL OR  desquamation_right IS NOT NULL OR  corn_right IS NOT NULL OR  deformity_right IS NOT NULL "
        +"        OR  pallus_right IS NOT NULL OR  infection_right IS NOT NULL OR nelon_right IS NOT NULL OR  vibra_right IS NOT NULL OR  ulcer_right IS NOT NULL"
        +"        )"
        +"        ) x"
        +"        GROUP BY x.examoid, x.vaexamtime"
        +"        ) t  "
        +"       ) sjbb "
        +"     ON fillter.exam_id=sjbb.examoid"
        +"     LEFT JOIN (SELECT  hp_info.hospital_id,area.explain_memo,area.firstping"
        +"                 FROM dash_g_t_dic_hospital_info hp_info"
        +"                 LEFT JOIN (SELECT  code,explain_memo,firstping  FROM hc_t_dic_area WHERE  LEFT (code,3)='310' AND level='3') area"
        +"                ON hp_info.address_county=area.code"
        +"                ) dic"
        +"     ON fillter.screen_hospital=dic.hospital_id"
        +"     ) xx ORDER BY per_card,vaexamtime DESC"
        +"    )xxx,(SELECT  @per_no := null ,@rank:=0) r "
        +" ) tt where tt.rank=1"
        +" GROUP BY county WITH ROLLUP "
    }
},

// 首页工作概况
sql['/api/home/workgeneral'] = {
    realtime: false,
    pool: pool.btdPool,
    sql: {
        // TODO sql 暂时提供神经病变和视网膜病变
        finish_number: "select count(distinct IF(sjbb.examoid IS not  NULL,concat( filter.personcard_no,filter.screen_hospital),null) ) sjbb_cnt, "
        +" count(distinct IF(swm.examoid IS not  NULL,concat( filter.personcard_no,filter.screen_hospital),null) ) swm_cnt "
        +" from"
        +" dash_g_dp_bfz_tw_filter  filter"
        +" left JOIN"
        +" dash_g_dp_bfz_tw_sjbb sjbb"
        +" ON filter.exam_id=sjbb.examoid"
        +" and sjbb.dry_left is not null"
        +" left JOIN"
        +" dash_g_dp_bfz_tw_swm swm"
        +" ON  filter.exam_id=swm.examoid and swm.diag_diab_yes_right is not null",
    }
}

// 内页工作概况
sql['/api/inside/workgeneral'] = {
    realtime: false,
    pool: pool.btdPool,
    sql: {
        // TODO sql 暂时提供神经病变和视网膜病变
        finish_number: "select county, "
        +" SUM(CASE WHEN flag='sjbb' THEN cnt ELSE 0 END ) sfbb_cnt, "
        +" SUM(CASE WHEN flag='swm' THEN cnt ELSE 0 END ) swm_cnt  "
        +" from "
        +" ("
        +" select "
        +" flag,"
        +" IF(dic_county.county IS NULL,'其它',dic_county.county) county,"
        +" hospital_info.hospital_name,"
        +" count(distinct zfx_report.hospital_id ,personcard_no) cnt "
        +" from "
        +" ("
        +" select distinct screen_hospital  hospital_id,  personcard_no, 'sjbb' as flag from "
        +" dash_g_dp_bfz_tw_filter  filter"
        +" inner JOIN"
        +" dash_g_dp_bfz_tw_sjbb sjbb"
        +" ON filter.exam_id=sjbb.examoid"
        +" and sjbb.dry_left is not null"
        +" union ALL"
        +" select distinct screen_hospital hospital_id ,  personcard_no, 'swm' as flag from "
        +" dash_g_dp_bfz_tw_filter  filter"
        +" inner JOIN"
        +" dash_g_dp_bfz_tw_swm swm"
        +" ON  filter.exam_id=swm.examoid and swm.diag_diab_yes_right is not null"
        +" ) zfx_report "
        +" right JOIN dash_g_t_dic_hospital_info hospital_info on zfx_report.hospital_id=hospital_info.hospital_id"
        +" and zfx_report.personcard_no is not null and zfx_report.hospital_id is not null"
        +" LEFT JOIN (SELECT code,IF(substr(code,1,3)='310',explain_memo,'其它') as county FROM hc_t_dic_area WHERE level='3') dic_county on hospital_info.address_county=dic_county.code"
        +" group by  IF(dic_county.county IS NULL,'其它',dic_county.county),zfx_report.hospital_id,hospital_info.hospital_name,flag"
        +" ) source "
        +" GROUP BY county"

    }
}


/*** 并发症筛查工作进度分析 **/
sql['/api/inside/analysis'] = {
    realtime: false,
    pool: pool.btdPool,
    sql: {
        /***---全市工作进度分析（周围神经和视网膜）*/
        allAnalysis:"select "
        +" B.dta ,"
        +" count(distinct case when sjbb.examoid IS not  NULL and filter.screen_date"
        +" BETWEEN DATE_SUB(CURDATE(),INTERVAL 12 MONTH) AND CURDATE() and DATE_FORMAT(filter.screen_date,'%Y%m') <= B.dta "
        +" then concat( filter.personcard_no,filter.screen_hospital) else null end ) AS sjbb_cnt,"
        +" count(distinct case when swm.examoid IS not  NULL and filter.screen_date"
        +" BETWEEN DATE_SUB(CURDATE(),INTERVAL 12 MONTH) AND CURDATE() and DATE_FORMAT(filter.screen_date,'%Y%m') <= B.dta "
        +" then concat( filter.personcard_no,filter.screen_hospital) else null end ) AS swm_cnt"
        +" from"
        +" dash_g_dp_bfz_tw_filter  filter"
        +" left JOIN"
        +" dash_g_dp_bfz_tw_sjbb sjbb"
        +" ON filter.exam_id=sjbb.examoid"
        +" and sjbb.dry_left is not null"
        +" left JOIN"
        +" dash_g_dp_bfz_tw_swm swm"
        +" ON  filter.exam_id=swm.examoid and swm.diag_diab_yes_right is not null"
        +" right JOIN"
        +" (SELECT distinct DATE_FORMAT(screen_date,'%Y%m')  dta FROM dash_g_dp_bfz_tw_filter  filter"
        +" where screen_date BETWEEN DATE_SUB(CURDATE(),INTERVAL 12 MONTH) AND CURDATE()"
        +" ) B"
        +" on 1=1"
        +" where filter.screen_date BETWEEN DATE_SUB(CURDATE(),INTERVAL 12 MONTH) AND CURDATE()"
        +" group by "
        +" B.dta",
        /***---各区县工作进度分析（周围神经和视网膜）*/
        areaAnalysis:"select "
        +" B.dta ,"
        +" IF(dic_county.county IS NULL,'其它',dic_county.county) AS county,"
        +" count(distinct case when sjbb.examoid IS not  NULL and filter.screen_date"
        +" BETWEEN DATE_SUB(CURDATE(),INTERVAL 12 MONTH) AND CURDATE() and DATE_FORMAT(filter.screen_date,'%Y%m') <= B.dta "
        +" then concat( filter.personcard_no,filter.screen_hospital) else null end ) AS sjbb_cnt,"
        +" count(distinct case when swm.examoid IS not  NULL and filter.screen_date"
        +" BETWEEN DATE_SUB(CURDATE(),INTERVAL 12 MONTH) AND CURDATE() and DATE_FORMAT(filter.screen_date,'%Y%m') <= B.dta "
        +" then concat( filter.personcard_no,filter.screen_hospital) else null end )AS swm_cnt"
        +" from"
        +" dash_g_dp_bfz_tw_filter  filter"
        +" left JOIN"
        +" dash_g_dp_bfz_tw_sjbb sjbb"
        +" ON filter.exam_id=sjbb.examoid"
        +" and sjbb.dry_left is not null"
        +" left JOIN"
        +" dash_g_dp_bfz_tw_swm swm"
        +" ON  filter.exam_id=swm.examoid and swm.diag_diab_yes_right is not null"
        +" right JOIN"
        +" (SELECT distinct DATE_FORMAT(screen_date,'%Y%m')  dta FROM dash_g_dp_bfz_tw_filter  filter"
        +" where screen_date BETWEEN DATE_SUB(CURDATE(),INTERVAL 12 MONTH) AND CURDATE()"
        +" ) B"
        +" on 1=1"
        +" right JOIN dash_g_t_dic_hospital_info hospital_info on filter.screen_hospital=hospital_info.hospital_id"
        +" LEFT JOIN (SELECT code,IF(substr(code,1,3)='310',explain_memo,'其它') as county FROM hc_t_dic_area WHERE level='3') dic_county on hospital_info.address_county=dic_county.code"
        +" where filter.screen_date BETWEEN DATE_SUB(CURDATE(),INTERVAL 12 MONTH) AND CURDATE()"
        +" group by "
        +" B.dta ,IF(dic_county.county IS NULL,'其它',dic_county.county)"

    }
},

/*** 并发症筛查完成情况 **/
sql['/api/inside/finished'] = {
        realtime: false,
        pool: pool.btdPool,
        sql: {
            /***---全市 （季度）  并发症筛查完成情况(周围神经）*/
            allFinishedSJBB :"SELECT '上海市' county "
            +" ,'YEAR' AS flag"
            +" ,YEAR(vaexamtime) AS stat_dt"
            +" ,COUNT(DISTINCT per_card) AS per_cnt  "
            +" FROM "
            +" ( SELECT CONCAT_WS(',',fillter.personcard_no,fillter.screen_hospital) AS per_card,sjbb.examoid,DATE(sjbb.vaexamtime) AS vaexamtime,sjbb.flag"
            +"   FROM dash_g_dp_bfz_tw_filter  fillter"
            +"   JOIN(SELECT  examoid,vaexamtime,foot_count,IF(foot_count>=6,3,IF(foot_count BETWEEN 4 AND 5,2,1)) flag "
            +"         FROM"
            +"         (SELECT  x.examoid,x.vaexamtime"
            +"           ,(IF(sum(dry_left + chap_left + desquamation_left + corn_left + deformity_left + pallus_left + infection_left)>= 1,1,sum(dry_left + chap_left + desquamation_left + corn_left + deformity_left + pallus_left + infection_left))"
            +"           + sum(nelon_left + ulcer_left + vibra_left)"
            +"           +IF(sum(dry_right + chap_right + desquamation_right + corn_right + deformity_right + pallus_right + infection_right)>= 1,1,sum(dry_right + chap_right + desquamation_right + corn_right + deformity_right + pallus_right + infection_right))"
            +"           + sum(nelon_right + vibra_right + ulcer_right)"
            +"           ) as foot_count"
            +"           FROM"
            +"           (SELECT "
            +"             examoid"
            +"             ,vaexamtime"
            +"             ,CASE WHEN dry_left = '2' THEN 0 WHEN dry_left = '1' THEN 0.5 ELSE 0 END  as dry_left "
            +"             ,CASE WHEN chap_left = '2' THEN 0 WHEN chap_left = '1' THEN 0.5 ELSE 0 END  as chap_left "
            +"             ,CASE WHEN desquamation_left = '2' THEN 0 WHEN desquamation_left = '1' THEN 0.5 ELSE 0 END as desquamation_left "
            +"             ,CASE WHEN corn_left = '2' THEN 0 WHEN corn_left = '1' THEN 1 ELSE 0 END as corn_left "
            +"             ,CASE WHEN deformity_left = '1' THEN 0 WHEN deformity_left IN('2','3','4','5') THEN 1 ELSE 0 END as deformity_left "
            +"             ,CASE WHEN pallus_left = '1' THEN 0 WHEN pallus_left IN('2','3','4') THEN 0.5 ELSE 0 END as pallus_left "
            +"             ,CASE WHEN infection_left = '2' THEN 	0 WHEN infection_left = '1' THEN 0.5 ELSE 0 END as infection_left 	"
            +"             ,CASE WHEN ulcer_left = '2' THEN 0 WHEN ulcer_left = '1' THEN 1 ELSE 0 END as ulcer_left "
            +"             ,CASE WHEN nelon_left = '1' THEN 0 WHEN nelon_left = '2' THEN 0.5 WHEN nelon_left = '3' THEN 1 ELSE 0 END as nelon_left	"
            +"             ,CASE WHEN vibra_left = '1' THEN 0 WHEN vibra_left = '2' THEN 0.5 WHEN vibra_left = '3' THEN 1 ELSE 0 END as vibra_left "
            +"             ,CASE WHEN dry_right = '2' THEN 0 WHEN dry_right = '1' THEN 0.5 ELSE 0 END as dry_right"
            +"             ,CASE WHEN chap_right = '2' THEN 0 WHEN chap_right = '1' THEN 0.5 ELSE 0 END as chap_right"
            +"             ,CASE WHEN desquamation_right = '2' THEN 0 WHEN desquamation_right = '1' THEN 0.5 ELSE 0 END as desquamation_right"
            +"             ,CASE WHEN corn_right = '2' THEN 0 WHEN corn_right = '1' THEN 1 ELSE 0 END as corn_right"
            +"             ,CASE WHEN deformity_right = '1' THEN 0 WHEN deformity_right IN('2','3','4','5') THEN 1 ELSE 0 END as deformity_right"
            +"             ,CASE WHEN pallus_right = '1' THEN 0.5 WHEN pallus_right IN('2','3','4') THEN 0 ELSE 0 END as pallus_right"
            +"             ,CASE WHEN infection_right = '2' THEN 0 WHEN infection_right = '1' THEN 0.5 ELSE 0 END as infection_right"
            +"             ,CASE WHEN ulcer_right = '2' THEN 0 WHEN ulcer_right = '1' THEN 1 ELSE 0 END as ulcer_right"
            +"             ,CASE WHEN nelon_right = '1' THEN 0 WHEN nelon_right = '2' THEN 0.5 WHEN nelon_right = '3' THEN 1 ELSE 0 END as nelon_right"
            +"             ,CASE WHEN vibra_right = '1' THEN 0 WHEN vibra_right = '2' THEN 0.5 WHEN vibra_right = '3' THEN 1 ELSE 0 END as vibra_right"
            +"             FROM dash_g_dp_bfz_tw_sjbb "
            +"             WHERE  (dry_left IS NOT NULL AND  chap_left IS NOT NULL AND  desquamation_left IS NOT NULL AND  corn_left IS NOT NULL AND  deformity_left IS NOT NULL "
            +"               AND  pallus_left IS NOT NULL AND  infection_left IS NOT NULL AND nelon_left IS NOT NULL AND  ulcer_left IS NOT NULL AND  vibra_left  IS NOT NULL "
            +"               AND dry_right IS NOT NULL AND  chap_right IS NOT NULL AND  desquamation_right IS NOT NULL AND  corn_right IS NOT NULL AND  deformity_right IS NOT NULL "
            +"               AND  pallus_right IS NOT NULL AND  infection_right IS NOT NULL AND nelon_right IS NOT NULL AND  vibra_right IS NOT NULL AND  ulcer_right IS NOT NULL)"
            +"           ) x"
            +"           GROUP BY x.examoid, x.vaexamtime"
            +"         ) t  "
            +"     ) sjbb "
            +"   ON fillter.exam_id=sjbb.examoid"
            +" ) xx  "
            +" WHERE vaexamtime BETWEEN  DATE_SUB(CURDATE(),INTERVAL 12 YEAR) AND CURDATE()"
            +" GROUP BY stat_dt"
            +" UNION ALL "
            +" SELECT '上海市' county"
            +" ,'MONTH' AS flag"
            +" ,LEFT(vaexamtime,7) AS stat_dt"
            +" ,COUNT(DISTINCT per_card) AS per_cnt  "
            +" FROM "
            +" ( SELECT CONCAT_WS(',',fillter.personcard_no,fillter.screen_hospital) AS per_card,sjbb.examoid,DATE(sjbb.vaexamtime) AS vaexamtime,sjbb.flag"
            +"   FROM dash_g_dp_bfz_tw_filter  fillter"
            +"   JOIN(SELECT  examoid,vaexamtime,foot_count,IF(foot_count>=6,3,IF(foot_count BETWEEN 4 AND 5,2,1)) flag "
            +"         FROM"
            +"         (SELECT  x.examoid,x.vaexamtime"
            +"           ,(IF(sum(dry_left + chap_left + desquamation_left + corn_left + deformity_left + pallus_left + infection_left)>= 1,1,sum(dry_left + chap_left + desquamation_left + corn_left + deformity_left + pallus_left + infection_left))"
            +"           + sum(nelon_left + ulcer_left + vibra_left)"
            +"           +IF(sum(dry_right + chap_right + desquamation_right + corn_right + deformity_right + pallus_right + infection_right)>= 1,1,sum(dry_right + chap_right + desquamation_right + corn_right + deformity_right + pallus_right + infection_right))"
            +"           + sum(nelon_right + vibra_right + ulcer_right)"
            +"           ) as foot_count"
            +"           FROM"
            +"           (SELECT "
            +"             examoid"
            +"             ,vaexamtime"
            +"             ,CASE WHEN dry_left = '2' THEN 0 WHEN dry_left = '1' THEN 0.5 ELSE 0 END  as dry_left "
            +"             ,CASE WHEN chap_left = '2' THEN 0 WHEN chap_left = '1' THEN 0.5 ELSE 0 END  as chap_left "
            +"             ,CASE WHEN desquamation_left = '2' THEN 0 WHEN desquamation_left = '1' THEN 0.5 ELSE 0 END as desquamation_left "
            +"             ,CASE WHEN corn_left = '2' THEN 0 WHEN corn_left = '1' THEN 1 ELSE 0 END as corn_left "
            +"             ,CASE WHEN deformity_left = '1' THEN 0 WHEN deformity_left IN('2','3','4','5') THEN 1 ELSE 0 END as deformity_left "
            +"             ,CASE WHEN pallus_left = '1' THEN 0 WHEN pallus_left IN('2','3','4') THEN 0.5 ELSE 0 END as pallus_left "
            +"             ,CASE WHEN infection_left = '2' THEN 	0 WHEN infection_left = '1' THEN 0.5 ELSE 0 END as infection_left 	"
            +"             ,CASE WHEN ulcer_left = '2' THEN 0 WHEN ulcer_left = '1' THEN 1 ELSE 0 END as ulcer_left "
            +"             ,CASE WHEN nelon_left = '1' THEN 0 WHEN nelon_left = '2' THEN 0.5 WHEN nelon_left = '3' THEN 1 ELSE 0 END as nelon_left	"
            +"             ,CASE WHEN vibra_left = '1' THEN 0 WHEN vibra_left = '2' THEN 0.5 WHEN vibra_left = '3' THEN 1 ELSE 0 END as vibra_left "
            +"             ,CASE WHEN dry_right = '2' THEN 0 WHEN dry_right = '1' THEN 0.5 ELSE 0 END as dry_right"
            +"             ,CASE WHEN chap_right = '2' THEN 0 WHEN chap_right = '1' THEN 0.5 ELSE 0 END as chap_right"
            +"             ,CASE WHEN desquamation_right = '2' THEN 0 WHEN desquamation_right = '1' THEN 0.5 ELSE 0 END as desquamation_right"
            +"             ,CASE WHEN corn_right = '2' THEN 0 WHEN corn_right = '1' THEN 1 ELSE 0 END as corn_right"
            +"             ,CASE WHEN deformity_right = '1' THEN 0 WHEN deformity_right IN('2','3','4','5') THEN 1 ELSE 0 END as deformity_right"
            +"             ,CASE WHEN pallus_right = '1' THEN 0.5 WHEN pallus_right IN('2','3','4') THEN 0 ELSE 0 END as pallus_right"
            +"             ,CASE WHEN infection_right = '2' THEN 0 WHEN infection_right = '1' THEN 0.5 ELSE 0 END as infection_right"
            +"             ,CASE WHEN ulcer_right = '2' THEN 0 WHEN ulcer_right = '1' THEN 1 ELSE 0 END as ulcer_right"
            +"             ,CASE WHEN nelon_right = '1' THEN 0 WHEN nelon_right = '2' THEN 0.5 WHEN nelon_right = '3' THEN 1 ELSE 0 END as nelon_right"
            +"             ,CASE WHEN vibra_right = '1' THEN 0 WHEN vibra_right = '2' THEN 0.5 WHEN vibra_right = '3' THEN 1 ELSE 0 END as vibra_right"
            +"             FROM dash_g_dp_bfz_tw_sjbb "
            +"             WHERE  (dry_left IS NOT NULL AND  chap_left IS NOT NULL AND  desquamation_left IS NOT NULL AND  corn_left IS NOT NULL AND  deformity_left IS NOT NULL "
            +"               AND  pallus_left IS NOT NULL AND  infection_left IS NOT NULL AND nelon_left IS NOT NULL AND  ulcer_left IS NOT NULL AND  vibra_left  IS NOT NULL "
            +"               AND dry_right IS NOT NULL AND  chap_right IS NOT NULL AND  desquamation_right IS NOT NULL AND  corn_right IS NOT NULL AND  deformity_right IS NOT NULL "
            +"               AND  pallus_right IS NOT NULL AND  infection_right IS NOT NULL AND nelon_right IS NOT NULL AND  vibra_right IS NOT NULL AND  ulcer_right IS NOT NULL)"
            +"           ) x"
            +"           GROUP BY x.examoid, x.vaexamtime"
            +"         ) t  "
            +"     ) sjbb "
            +"   ON fillter.exam_id=sjbb.examoid"
            +" ) xx  "
            +" WHERE vaexamtime BETWEEN  DATE_SUB(CURDATE(),INTERVAL 12 MONTH) AND CURDATE()"
            +" GROUP BY stat_dt"
            +" UNION ALL "
            +" SELECT '上海市' county"
            +" ,'QUARTER' AS flag"
            +" ,CONCAT(YEAR(vaexamtime),'Q',QUARTER(vaexamtime)) AS stat_dt"
            +" ,COUNT(DISTINCT per_card) AS per_cnt "
            +" FROM "
            +" ( SELECT CONCAT_WS(',',fillter.personcard_no,fillter.screen_hospital) AS per_card,sjbb.examoid,DATE(sjbb.vaexamtime) AS vaexamtime,sjbb.flag"
            +"   FROM dash_g_dp_bfz_tw_filter  fillter"
            +"   JOIN(SELECT  examoid,vaexamtime,foot_count,IF(foot_count>=6,3,IF(foot_count BETWEEN 4 AND 5,2,1)) flag "
            +"         FROM"
            +"         (SELECT  x.examoid,x.vaexamtime"
            +"           ,(IF(sum(dry_left + chap_left + desquamation_left + corn_left + deformity_left + pallus_left + infection_left)>= 1,1,sum(dry_left + chap_left + desquamation_left + corn_left + deformity_left + pallus_left + infection_left))"
            +"           + sum(nelon_left + ulcer_left + vibra_left)"
            +"           +IF(sum(dry_right + chap_right + desquamation_right + corn_right + deformity_right + pallus_right + infection_right)>= 1,1,sum(dry_right + chap_right + desquamation_right + corn_right + deformity_right + pallus_right + infection_right))"
            +"           + sum(nelon_right + vibra_right + ulcer_right)"
            +"           ) as foot_count"
            +"           FROM"
            +"           (SELECT "
            +"             examoid"
            +"             ,vaexamtime"
            +"             ,CASE WHEN dry_left = '2' THEN 0 WHEN dry_left = '1' THEN 0.5 ELSE 0 END  as dry_left "
            +"             ,CASE WHEN chap_left = '2' THEN 0 WHEN chap_left = '1' THEN 0.5 ELSE 0 END  as chap_left "
            +"             ,CASE WHEN desquamation_left = '2' THEN 0 WHEN desquamation_left = '1' THEN 0.5 ELSE 0 END as desquamation_left"
            +"             ,CASE WHEN corn_left = '2' THEN 0 WHEN corn_left = '1' THEN 1 ELSE 0 END as corn_left "
            +"             ,CASE WHEN deformity_left = '1' THEN 0 WHEN deformity_left IN('2','3','4','5') THEN 1 ELSE 0 END as deformity_left "
            +"             ,CASE WHEN pallus_left = '1' THEN 0 WHEN pallus_left IN('2','3','4') THEN 0.5 ELSE 0 END as pallus_left "
            +"             ,CASE WHEN infection_left = '2' THEN 	0 WHEN infection_left = '1' THEN 0.5 ELSE 0 END as infection_left 	"
            +"             ,CASE WHEN ulcer_left = '2' THEN 0 WHEN ulcer_left = '1' THEN 1 ELSE 0 END as ulcer_left "
            +"             ,CASE WHEN nelon_left = '1' THEN 0 WHEN nelon_left = '2' THEN 0.5 WHEN nelon_left = '3' THEN 1 ELSE 0 END as nelon_left	"
            +"             ,CASE WHEN vibra_left = '1' THEN 0 WHEN vibra_left = '2' THEN 0.5 WHEN vibra_left = '3' THEN 1 ELSE 0 END as vibra_left "
            +"             ,CASE WHEN dry_right = '2' THEN 0 WHEN dry_right = '1' THEN 0.5 ELSE 0 END as dry_right"
            +"             ,CASE WHEN chap_right = '2' THEN 0 WHEN chap_right = '1' THEN 0.5 ELSE 0 END as chap_right"
            +"             ,CASE WHEN desquamation_right = '2' THEN 0 WHEN desquamation_right = '1' THEN 0.5 ELSE 0 END as desquamation_right"
            +"             ,CASE WHEN corn_right = '2' THEN 0 WHEN corn_right = '1' THEN 1 ELSE 0 END as corn_right"
            +"             ,CASE WHEN deformity_right = '1' THEN 0 WHEN deformity_right IN('2','3','4','5') THEN 1 ELSE 0 END as deformity_right"
            +"             ,CASE WHEN pallus_right = '1' THEN 0.5 WHEN pallus_right IN('2','3','4') THEN 0 ELSE 0 END as pallus_right"
            +"             ,CASE WHEN infection_right = '2' THEN 0 WHEN infection_right = '1' THEN 0.5 ELSE 0 END as infection_right"
            +"             ,CASE WHEN ulcer_right = '2' THEN 0 WHEN ulcer_right = '1' THEN 1 ELSE 0 END as ulcer_right"
            +"             ,CASE WHEN nelon_right = '1' THEN 0 WHEN nelon_right = '2' THEN 0.5 WHEN nelon_right = '3' THEN 1 ELSE 0 END as nelon_right"
            +"             ,CASE WHEN vibra_right = '1' THEN 0 WHEN vibra_right = '2' THEN 0.5 WHEN vibra_right = '3' THEN 1 ELSE 0 END as vibra_right"
            +"             FROM dash_g_dp_bfz_tw_sjbb "
            +"             WHERE  (dry_left IS NOT NULL AND  chap_left IS NOT NULL AND  desquamation_left IS NOT NULL AND  corn_left IS NOT NULL AND  deformity_left IS NOT NULL "
            +"               AND  pallus_left IS NOT NULL AND  infection_left IS NOT NULL AND nelon_left IS NOT NULL AND  ulcer_left IS NOT NULL AND  vibra_left  IS NOT NULL "
            +"               AND dry_right IS NOT NULL AND  chap_right IS NOT NULL AND  desquamation_right IS NOT NULL AND  corn_right IS NOT NULL AND  deformity_right IS NOT NULL "
            +"               AND  pallus_right IS NOT NULL AND  infection_right IS NOT NULL AND nelon_right IS NOT NULL AND  vibra_right IS NOT NULL AND  ulcer_right IS NOT NULL)"
            +"           ) x"
            +"           GROUP BY x.examoid, x.vaexamtime"
            +"         ) t  "
            +"     ) sjbb "
            +"   ON fillter.exam_id=sjbb.examoid"
            +" ) xx  "
            +" WHERE vaexamtime BETWEEN  DATE_SUB(CURDATE(),INTERVAL 3 YEAR) AND CURDATE()"
            +" GROUP BY stat_dt",
            /*** 各区县并发症筛查完成情况(周围神经) **/
            areaFinishedSJBB:"SELECT county "
            +" ,'YEAR' AS flag"
            +" ,YEAR(vaexamtime) AS stat_dt"
            +" ,COUNT(DISTINCT per_card) AS per_cnt  "
            +" FROM "
            +" ( SELECT CONCAT_WS(',',fillter.personcard_no,fillter.screen_hospital) AS per_card,sjbb.examoid,DATE(sjbb.vaexamtime) AS vaexamtime,sjbb.flag,dic.explain_memo as county"
            +"   FROM dash_g_dp_bfz_tw_filter  fillter"
            +"   JOIN(SELECT  examoid,vaexamtime,foot_count,IF(foot_count>=6,3,IF(foot_count BETWEEN 4 AND 5,2,1)) flag "
            +"         FROM"
            +"         (SELECT  x.examoid,x.vaexamtime"
            +"           ,(IF(sum(dry_left + chap_left + desquamation_left + corn_left + deformity_left + pallus_left + infection_left)>= 1,1,sum(dry_left + chap_left + desquamation_left + corn_left + deformity_left + pallus_left + infection_left))"
            +"           + sum(nelon_left + ulcer_left + vibra_left)"
            +"           +IF(sum(dry_right + chap_right + desquamation_right + corn_right + deformity_right + pallus_right + infection_right)>= 1,1,sum(dry_right + chap_right + desquamation_right + corn_right + deformity_right + pallus_right + infection_right))"
            +"           + sum(nelon_right + vibra_right + ulcer_right)"
            +"           ) as foot_count"
            +"           FROM"
            +"           (SELECT "
            +"             examoid"
            +"             ,vaexamtime"
            +"             ,CASE WHEN dry_left = '2' THEN 0 WHEN dry_left = '1' THEN 0.5 ELSE 0 END  as dry_left "
            +"             ,CASE WHEN chap_left = '2' THEN 0 WHEN chap_left = '1' THEN 0.5 ELSE 0 END  as chap_left "
            +"             ,CASE WHEN desquamation_left = '2' THEN 0 WHEN desquamation_left = '1' THEN 0.5 ELSE 0 END as desquamation_left "
            +"             ,CASE WHEN corn_left = '2' THEN 0 WHEN corn_left = '1' THEN 1 ELSE 0 END as corn_left "
            +"             ,CASE WHEN deformity_left = '1' THEN 0 WHEN deformity_left IN('2','3','4','5') THEN 1 ELSE 0 END as deformity_left "
            +"             ,CASE WHEN pallus_left = '1' THEN 0 WHEN pallus_left IN('2','3','4') THEN 0.5 ELSE 0 END as pallus_left "
            +"             ,CASE WHEN infection_left = '2' THEN 	0 WHEN infection_left = '1' THEN 0.5 ELSE 0 END as infection_left 	"
            +"             ,CASE WHEN ulcer_left = '2' THEN 0 WHEN ulcer_left = '1' THEN 1 ELSE 0 END as ulcer_left "
            +"             ,CASE WHEN nelon_left = '1' THEN 0 WHEN nelon_left = '2' THEN 0.5 WHEN nelon_left = '3' THEN 1 ELSE 0 END as nelon_left	"
            +"             ,CASE WHEN vibra_left = '1' THEN 0 WHEN vibra_left = '2' THEN 0.5 WHEN vibra_left = '3' THEN 1 ELSE 0 END as vibra_left "
            +"             ,CASE WHEN dry_right = '2' THEN 0 WHEN dry_right = '1' THEN 0.5 ELSE 0 END as dry_right"
            +"             ,CASE WHEN chap_right = '2' THEN 0 WHEN chap_right = '1' THEN 0.5 ELSE 0 END as chap_right"
            +"             ,CASE WHEN desquamation_right = '2' THEN 0 WHEN desquamation_right = '1' THEN 0.5 ELSE 0 END as desquamation_right"
            +"             ,CASE WHEN corn_right = '2' THEN 0 WHEN corn_right = '1' THEN 1 ELSE 0 END as corn_right"
            +"             ,CASE WHEN deformity_right = '1' THEN 0 WHEN deformity_right IN('2','3','4','5') THEN 1 ELSE 0 END as deformity_right"
            +"             ,CASE WHEN pallus_right = '1' THEN 0.5 WHEN pallus_right IN('2','3','4') THEN 0 ELSE 0 END as pallus_right"
            +"             ,CASE WHEN infection_right = '2' THEN 0 WHEN infection_right = '1' THEN 0.5 ELSE 0 END as infection_right"
            +"             ,CASE WHEN ulcer_right = '2' THEN 0 WHEN ulcer_right = '1' THEN 1 ELSE 0 END as ulcer_right"
            +"             ,CASE WHEN nelon_right = '1' THEN 0 WHEN nelon_right = '2' THEN 0.5 WHEN nelon_right = '3' THEN 1 ELSE 0 END as nelon_right"
            +"             ,CASE WHEN vibra_right = '1' THEN 0 WHEN vibra_right = '2' THEN 0.5 WHEN vibra_right = '3' THEN 1 ELSE 0 END as vibra_right"
            +"             FROM dash_g_dp_bfz_tw_sjbb "
            +"             WHERE  (dry_left IS NOT NULL AND  chap_left IS NOT NULL AND  desquamation_left IS NOT NULL AND  corn_left IS NOT NULL AND  deformity_left IS NOT NULL "
            +"               AND  pallus_left IS NOT NULL AND  infection_left IS NOT NULL AND nelon_left IS NOT NULL AND  ulcer_left IS NOT NULL AND  vibra_left  IS NOT NULL "
            +"               AND dry_right IS NOT NULL AND  chap_right IS NOT NULL AND  desquamation_right IS NOT NULL AND  corn_right IS NOT NULL AND  deformity_right IS NOT NULL "
            +"               AND  pallus_right IS NOT NULL AND  infection_right IS NOT NULL AND nelon_right IS NOT NULL AND  vibra_right IS NOT NULL AND  ulcer_right IS NOT NULL)"
            +"           ) x"
            +"           GROUP BY x.examoid, x.vaexamtime"
            +"         ) t  "
            +"     ) sjbb "
            +"   ON fillter.exam_id=sjbb.examoid"
            +"   LEFT JOIN (SELECT  hp_info.hospital_id,area.explain_memo,area.firstping"
            +"               FROM dash_g_t_dic_hospital_info hp_info"
            +"               LEFT JOIN (SELECT  code,explain_memo,firstping  FROM hc_t_dic_area WHERE  LEFT (code,3)='310' AND level='3') area"
            +"              ON hp_info.address_county=area.code"
            +"              ) dic"
            +"   ON fillter.screen_hospital=dic.hospital_id"
            +" ) xx  "
            +" WHERE vaexamtime BETWEEN  DATE_SUB(CURDATE(),INTERVAL 12 YEAR) AND CURDATE()"
            +" GROUP BY stat_dt,county"
            +" UNION ALL "
            +" SELECT county"
            +" ,'MONTH' AS flag"
            +" ,LEFT(vaexamtime,7) AS stat_dt"
            +" ,COUNT(DISTINCT per_card) AS per_cnt  "
            +" FROM "
            +" ( SELECT CONCAT_WS(',',fillter.personcard_no,fillter.screen_hospital) AS per_card,sjbb.examoid,DATE(sjbb.vaexamtime) AS vaexamtime,sjbb.flag,dic.explain_memo as county"
            +"   FROM dash_g_dp_bfz_tw_filter  fillter"
            +"   JOIN(SELECT  examoid,vaexamtime,foot_count,IF(foot_count>=6,3,IF(foot_count BETWEEN 4 AND 5,2,1)) flag "
            +"         FROM"
            +"         (SELECT  x.examoid,x.vaexamtime"
            +"           ,(IF(sum(dry_left + chap_left + desquamation_left + corn_left + deformity_left + pallus_left + infection_left)>= 1,1,sum(dry_left + chap_left + desquamation_left + corn_left + deformity_left + pallus_left + infection_left))"
            +"           + sum(nelon_left + ulcer_left + vibra_left)"
            +"           +IF(sum(dry_right + chap_right + desquamation_right + corn_right + deformity_right + pallus_right + infection_right)>= 1,1,sum(dry_right + chap_right + desquamation_right + corn_right + deformity_right + pallus_right + infection_right))"
            +"           + sum(nelon_right + vibra_right + ulcer_right)"
            +"           ) as foot_count"
            +"           FROM"
            +"           (SELECT "
            +"             examoid"
            +"             ,vaexamtime"
            +"             ,CASE WHEN dry_left = '2' THEN 0 WHEN dry_left = '1' THEN 0.5 ELSE 0 END  as dry_left "
            +"             ,CASE WHEN chap_left = '2' THEN 0 WHEN chap_left = '1' THEN 0.5 ELSE 0 END  as chap_left "
            +"             ,CASE WHEN desquamation_left = '2' THEN 0 WHEN desquamation_left = '1' THEN 0.5 ELSE 0 END as desquamation_left "
            +"             ,CASE WHEN corn_left = '2' THEN 0 WHEN corn_left = '1' THEN 1 ELSE 0 END as corn_left "
            +"             ,CASE WHEN deformity_left = '1' THEN 0 WHEN deformity_left IN('2','3','4','5') THEN 1 ELSE 0 END as deformity_left "
            +"             ,CASE WHEN pallus_left = '1' THEN 0 WHEN pallus_left IN('2','3','4') THEN 0.5 ELSE 0 END as pallus_left "
            +"             ,CASE WHEN infection_left = '2' THEN 	0 WHEN infection_left = '1' THEN 0.5 ELSE 0 END as infection_left 	"
            +"             ,CASE WHEN ulcer_left = '2' THEN 0 WHEN ulcer_left = '1' THEN 1 ELSE 0 END as ulcer_left"
            +"             ,CASE WHEN nelon_left = '1' THEN 0 WHEN nelon_left = '2' THEN 0.5 WHEN nelon_left = '3' THEN 1 ELSE 0 END as nelon_left	"
            +"             ,CASE WHEN vibra_left = '1' THEN 0 WHEN vibra_left = '2' THEN 0.5 WHEN vibra_left = '3' THEN 1 ELSE 0 END as vibra_left "
            +"             ,CASE WHEN dry_right = '2' THEN 0 WHEN dry_right = '1' THEN 0.5 ELSE 0 END as dry_right"
            +"             ,CASE WHEN chap_right = '2' THEN 0 WHEN chap_right = '1' THEN 0.5 ELSE 0 END as chap_right"
            +"             ,CASE WHEN desquamation_right = '2' THEN 0 WHEN desquamation_right = '1' THEN 0.5 ELSE 0 END as desquamation_right"
            +"             ,CASE WHEN corn_right = '2' THEN 0 WHEN corn_right = '1' THEN 1 ELSE 0 END as corn_right"
            +"             ,CASE WHEN deformity_right = '1' THEN 0 WHEN deformity_right IN('2','3','4','5') THEN 1 ELSE 0 END as deformity_right"
            +"             ,CASE WHEN pallus_right = '1' THEN 0.5 WHEN pallus_right IN('2','3','4') THEN 0 ELSE 0 END as pallus_right"
            +"             ,CASE WHEN infection_right = '2' THEN 0 WHEN infection_right = '1' THEN 0.5 ELSE 0 END as infection_right"
            +"             ,CASE WHEN ulcer_right = '2' THEN 0 WHEN ulcer_right = '1' THEN 1 ELSE 0 END as ulcer_right"
            +"             ,CASE WHEN nelon_right = '1' THEN 0 WHEN nelon_right = '2' THEN 0.5 WHEN nelon_right = '3' THEN 1 ELSE 0 END as nelon_right"
            +"             ,CASE WHEN vibra_right = '1' THEN 0 WHEN vibra_right = '2' THEN 0.5 WHEN vibra_right = '3' THEN 1 ELSE 0 END as vibra_right"
            +"             FROM dash_g_dp_bfz_tw_sjbb "
            +"             WHERE  (dry_left IS NOT NULL AND  chap_left IS NOT NULL AND  desquamation_left IS NOT NULL AND  corn_left IS NOT NULL AND  deformity_left IS NOT NULL "
            +"               AND  pallus_left IS NOT NULL AND  infection_left IS NOT NULL AND nelon_left IS NOT NULL AND  ulcer_left IS NOT NULL AND  vibra_left  IS NOT NULL "
            +"               AND dry_right IS NOT NULL AND  chap_right IS NOT NULL AND  desquamation_right IS NOT NULL AND  corn_right IS NOT NULL AND  deformity_right IS NOT NULL "
            +"               AND  pallus_right IS NOT NULL AND  infection_right IS NOT NULL AND nelon_right IS NOT NULL AND  vibra_right IS NOT NULL AND  ulcer_right IS NOT NULL)"
            +"           ) x"
            +"           GROUP BY x.examoid, x.vaexamtime"
            +"         ) t  "
            +"     ) sjbb "
            +"   ON fillter.exam_id=sjbb.examoid"
            +"   LEFT JOIN (SELECT  hp_info.hospital_id,area.explain_memo,area.firstping"
            +"               FROM dash_g_t_dic_hospital_info hp_info"
            +"               LEFT JOIN (SELECT  code,explain_memo,firstping  FROM hc_t_dic_area WHERE  LEFT (code,3)='310' AND level='3') area"
            +"              ON hp_info.address_county=area.code"
            +"              ) dic"
            +"   ON fillter.screen_hospital=dic.hospital_id  "
            +" ) xx  "
            +" WHERE vaexamtime BETWEEN  DATE_SUB(CURDATE(),INTERVAL 12 MONTH) AND CURDATE()"
            +" GROUP BY stat_dt,county"
            +" UNION ALL "
            +" SELECT county"
            +" ,'QUARTER' AS flag"
            +" ,CONCAT(YEAR(vaexamtime),'Q',QUARTER(vaexamtime)) AS stat_dt"
            +" ,COUNT(DISTINCT per_card) AS per_cnt  "
            +" FROM "
            +" ( SELECT CONCAT_WS(',',fillter.personcard_no,fillter.screen_hospital) AS per_card,sjbb.examoid,DATE(sjbb.vaexamtime) AS vaexamtime,sjbb.flag,dic.explain_memo as county"
            +"   FROM dash_g_dp_bfz_tw_filter  fillter"
            +"   JOIN(SELECT  examoid,vaexamtime,foot_count,IF(foot_count>=6,3,IF(foot_count BETWEEN 4 AND 5,2,1)) flag "
            +"         FROM"
            +"         (SELECT  x.examoid,x.vaexamtime"
            +"           ,(IF(sum(dry_left + chap_left + desquamation_left + corn_left + deformity_left + pallus_left + infection_left)>= 1,1,sum(dry_left + chap_left + desquamation_left + corn_left + deformity_left + pallus_left + infection_left))"
            +"           + sum(nelon_left + ulcer_left + vibra_left)"
            +"           +IF(sum(dry_right + chap_right + desquamation_right + corn_right + deformity_right + pallus_right + infection_right)>= 1,1,sum(dry_right + chap_right + desquamation_right + corn_right + deformity_right + pallus_right + infection_right))"
            +"           + sum(nelon_right + vibra_right + ulcer_right)"
            +"           ) as foot_count"
            +"           FROM"
            +"           (SELECT "
            +"             examoid"
            +"             ,vaexamtime"
            +"             ,CASE WHEN dry_left = '2' THEN 0 WHEN dry_left = '1' THEN 0.5 ELSE 0 END  as dry_left "
            +"             ,CASE WHEN chap_left = '2' THEN 0 WHEN chap_left = '1' THEN 0.5 ELSE 0 END  as chap_left "
            +"             ,CASE WHEN desquamation_left = '2' THEN 0 WHEN desquamation_left = '1' THEN 0.5 ELSE 0 END as desquamation_left "
            +"             ,CASE WHEN corn_left = '2' THEN 0 WHEN corn_left = '1' THEN 1 ELSE 0 END as corn_left "
            +"             ,CASE WHEN deformity_left = '1' THEN 0 WHEN deformity_left IN('2','3','4','5') THEN 1 ELSE 0 END as deformity_left "
            +"             ,CASE WHEN pallus_left = '1' THEN 0 WHEN pallus_left IN('2','3','4') THEN 0.5 ELSE 0 END as pallus_left "
            +"             ,CASE WHEN infection_left = '2' THEN 	0 WHEN infection_left = '1' THEN 0.5 ELSE 0 END as infection_left "
            +"             ,CASE WHEN ulcer_left = '2' THEN 0 WHEN ulcer_left = '1' THEN 1 ELSE 0 END as ulcer_left "
            +"             ,CASE WHEN nelon_left = '1' THEN 0 WHEN nelon_left = '2' THEN 0.5 WHEN nelon_left = '3' THEN 1 ELSE 0 END as nelon_left	"
            +"             ,CASE WHEN vibra_left = '1' THEN 0 WHEN vibra_left = '2' THEN 0.5 WHEN vibra_left = '3' THEN 1 ELSE 0 END as vibra_left "
            +"             ,CASE WHEN dry_right = '2' THEN 0 WHEN dry_right = '1' THEN 0.5 ELSE 0 END as dry_right"
            +"             ,CASE WHEN chap_right = '2' THEN 0 WHEN chap_right = '1' THEN 0.5 ELSE 0 END as chap_right"
            +"             ,CASE WHEN desquamation_right = '2' THEN 0 WHEN desquamation_right = '1' THEN 0.5 ELSE 0 END as desquamation_right"
            +"             ,CASE WHEN corn_right = '2' THEN 0 WHEN corn_right = '1' THEN 1 ELSE 0 END as corn_right"
            +"             ,CASE WHEN deformity_right = '1' THEN 0 WHEN deformity_right IN('2','3','4','5') THEN 1 ELSE 0 END as deformity_right"
            +"             ,CASE WHEN pallus_right = '1' THEN 0.5 WHEN pallus_right IN('2','3','4') THEN 0 ELSE 0 END as pallus_right"
            +"             ,CASE WHEN infection_right = '2' THEN 0 WHEN infection_right = '1' THEN 0.5 ELSE 0 END as infection_right"
            +"             ,CASE WHEN ulcer_right = '2' THEN 0 WHEN ulcer_right = '1' THEN 1 ELSE 0 END as ulcer_right"
            +"             ,CASE WHEN nelon_right = '1' THEN 0 WHEN nelon_right = '2' THEN 0.5 WHEN nelon_right = '3' THEN 1 ELSE 0 END as nelon_right"
            +"             ,CASE WHEN vibra_right = '1' THEN 0 WHEN vibra_right = '2' THEN 0.5 WHEN vibra_right = '3' THEN 1 ELSE 0 END as vibra_right"
            +"             FROM dash_g_dp_bfz_tw_sjbb "
            +"             WHERE  (dry_left IS NOT NULL AND  chap_left IS NOT NULL AND  desquamation_left IS NOT NULL AND  corn_left IS NOT NULL AND  deformity_left IS NOT NULL "
            +"               AND  pallus_left IS NOT NULL AND  infection_left IS NOT NULL AND nelon_left IS NOT NULL AND  ulcer_left IS NOT NULL AND  vibra_left  IS NOT NULL "
            +"               AND dry_right IS NOT NULL AND  chap_right IS NOT NULL AND  desquamation_right IS NOT NULL AND  corn_right IS NOT NULL AND  deformity_right IS NOT NULL "
            +"               AND  pallus_right IS NOT NULL AND  infection_right IS NOT NULL AND nelon_right IS NOT NULL AND  vibra_right IS NOT NULL AND  ulcer_right IS NOT NULL)"
            +"           ) x"
            +"           GROUP BY x.examoid, x.vaexamtime"
            +"         ) t  "
            +"     ) sjbb "
            +"   ON fillter.exam_id=sjbb.examoid"
            +"   LEFT JOIN (SELECT  hp_info.hospital_id,area.explain_memo,area.firstping"
            +"               FROM dash_g_t_dic_hospital_info hp_info"
            +"               LEFT JOIN (SELECT  code,explain_memo,firstping  FROM hc_t_dic_area WHERE  LEFT (code,3)='310' AND level='3') area"
            +"              ON hp_info.address_county=area.code"
            +"              ) dic"
            +"   ON fillter.screen_hospital=dic.hospital_id  "
            +" ) xx  "
            +" WHERE vaexamtime BETWEEN  DATE_SUB(CURDATE(),INTERVAL 3 YEAR) AND CURDATE()"
            +" GROUP BY stat_dt,county",
            /*** 全市并发症筛查完成情况(视网膜) **/
            allFinishedSWM:"SELECT '上海市' county "
            +" ,'YEAR' AS flag"
            +" ,YEAR(vaexamtime) AS stat_dt"
            +" ,COUNT(DISTINCT per_card) AS per_cnt  "
            +" FROM"
            +" (SELECT   CONCAT_WS(',',fillter.personcard_no,fillter.screen_hospital) AS per_card,swm.examoid,swm.exam_date AS vaexamtime"
            +"     FROM dash_g_dp_bfz_tw_filter  fillter"
            +"     JOIN(SELECT examoid, eyegroundexamtime exam_date FROM dash_g_dp_bfz_tw_swm WHERE (diag_diab_yes_right IS NOT NULL  OR diag_diab_yes_left IS NOT NULL )) swm "
            +"     ON fillter.exam_id=swm.examoid"
            +" ) xx  "
            +" WHERE vaexamtime BETWEEN  DATE_SUB(CURDATE(),INTERVAL 12 YEAR) AND CURDATE()"
            +" GROUP BY stat_dt"
            +" UNION ALL "
            +" SELECT '上海市' county "
            +" ,'MONTH' AS flag"
            +" ,LEFT(vaexamtime,7) AS stat_dt"
            +" ,COUNT(DISTINCT per_card) AS per_cnt  "
            +" FROM"
            +" (SELECT   CONCAT_WS(',',fillter.personcard_no,fillter.screen_hospital) AS per_card,swm.examoid,swm.exam_date AS vaexamtime"
            +"     FROM dash_g_dp_bfz_tw_filter  fillter"
            +"     JOIN(SELECT examoid, eyegroundexamtime exam_date FROM dash_g_dp_bfz_tw_swm WHERE (diag_diab_yes_right IS NOT NULL  OR diag_diab_yes_left IS NOT NULL )) swm "
            +"     ON fillter.exam_id=swm.examoid"
            +" ) xx  "
            +" WHERE vaexamtime BETWEEN  DATE_SUB(CURDATE(),INTERVAL 12 MONTH) AND CURDATE()"
            +" GROUP BY stat_dt"
            +" UNION ALL "
            +" SELECT '上海市' county "
            +" ,'QUARTER' AS flag"
            +" ,CONCAT(YEAR(vaexamtime),'Q',QUARTER(vaexamtime)) AS stat_dt"
            +" ,COUNT(DISTINCT per_card) AS per_cnt  "
            +" FROM"
            +" (SELECT   CONCAT_WS(',',fillter.personcard_no,fillter.screen_hospital) AS per_card,swm.examoid,swm.exam_date AS vaexamtime"
            +"     FROM dash_g_dp_bfz_tw_filter  fillter"
            +"     JOIN(SELECT examoid, eyegroundexamtime exam_date FROM dash_g_dp_bfz_tw_swm WHERE (diag_diab_yes_right IS NOT NULL  OR diag_diab_yes_left IS NOT NULL )) swm "
            +"     ON fillter.exam_id=swm.examoid"
            +" ) xx  "
            +" WHERE vaexamtime BETWEEN  DATE_SUB(CURDATE(),INTERVAL 3 YEAR) AND CURDATE()"
            +" GROUP BY stat_dt",
            /*** 各区县并发症筛查完成情况(视网膜) **/
            areaFinishedSWM:"SELECT county "
            +" ,'YEAR' AS flag"
            +" ,YEAR(vaexamtime) AS stat_dt"
            +" ,COUNT(DISTINCT per_card) AS per_cnt  "
            +" FROM"
            +" (SELECT   CONCAT_WS(',',fillter.personcard_no,fillter.screen_hospital) AS per_card,dic.explain_memo as county,swm.examoid,swm.exam_date AS vaexamtime"
            +"     FROM dash_g_dp_bfz_tw_filter  fillter"
            +"     JOIN(SELECT examoid, eyegroundexamtime exam_date FROM dash_g_dp_bfz_tw_swm WHERE (diag_diab_yes_right IS NOT NULL  OR diag_diab_yes_left IS NOT NULL )) swm "
            +"     ON fillter.exam_id=swm.examoid"
            +"     LEFT JOIN (SELECT  hp_info.hospital_id,area.explain_memo,area.firstping"
            +"                FROM dash_g_t_dic_hospital_info hp_info"
            +"                LEFT JOIN (SELECT  code,explain_memo,firstping  FROM hc_t_dic_area WHERE  LEFT (code,3)='310' AND level='3') area"
            +"               ON hp_info.address_county=area.code"
            +"               ) dic"
            +"    ON fillter.screen_hospital=dic.hospital_id"
            +" ) xx  "
            +" WHERE vaexamtime BETWEEN  DATE_SUB(CURDATE(),INTERVAL 12 YEAR) AND CURDATE()"
            +" GROUP BY stat_dt,county"
            +" UNION ALL "
            +" SELECT county "
            +" ,'MONTH' AS flag"
            +" ,LEFT(vaexamtime,7) AS stat_dt"
            +" ,COUNT(DISTINCT per_card) AS per_cnt  "
            +" FROM"
            +" (SELECT   CONCAT_WS(',',fillter.personcard_no,fillter.screen_hospital) AS per_card,dic.explain_memo as county,swm.examoid,swm.exam_date AS vaexamtime"
            +"     FROM dash_g_dp_bfz_tw_filter  fillter"
            +"     JOIN(SELECT examoid, eyegroundexamtime exam_date FROM dash_g_dp_bfz_tw_swm WHERE (diag_diab_yes_right IS NOT NULL  OR diag_diab_yes_left IS NOT NULL )) swm "
            +"     ON fillter.exam_id=swm.examoid"
            +"     LEFT JOIN (SELECT  hp_info.hospital_id,area.explain_memo,area.firstping"
            +"                FROM dash_g_t_dic_hospital_info hp_info"
            +"                LEFT JOIN (SELECT  code,explain_memo,firstping  FROM hc_t_dic_area WHERE  LEFT (code,3)='310' AND level='3') area"
            +"               ON hp_info.address_county=area.code"
            +"               ) dic"
            +"    ON fillter.screen_hospital=dic.hospital_id"
            +" ) xx  "
            +" WHERE vaexamtime BETWEEN  DATE_SUB(CURDATE(),INTERVAL 12 MONTH) AND CURDATE()"
            +" GROUP BY stat_dt,county"
            +" UNION ALL "
            +" SELECT county "
            +" ,'QUARTER' AS flag"
            +" ,CONCAT(YEAR(vaexamtime),'Q',QUARTER(vaexamtime)) AS stat_dt"
            +" ,COUNT(DISTINCT per_card) AS per_cnt  "
            +" FROM"
            +" (SELECT   CONCAT_WS(',',fillter.personcard_no,fillter.screen_hospital) AS per_card,dic.explain_memo as county,swm.examoid,swm.exam_date AS vaexamtime"
            +"     FROM dash_g_dp_bfz_tw_filter  fillter"
            +"     JOIN(SELECT examoid, eyegroundexamtime exam_date FROM dash_g_dp_bfz_tw_swm WHERE (diag_diab_yes_right IS NOT NULL  OR diag_diab_yes_left IS NOT NULL )) swm "
            +"     ON fillter.exam_id=swm.examoid"
            +"     LEFT JOIN (SELECT  hp_info.hospital_id,area.explain_memo,area.firstping"
            +"                FROM dash_g_t_dic_hospital_info hp_info"
            +"                LEFT JOIN (SELECT  code,explain_memo,firstping  FROM hc_t_dic_area WHERE  LEFT (code,3)='310' AND level='3') area"
            +"               ON hp_info.address_county=area.code"
            +"               ) dic"
            +"    ON fillter.screen_hospital=dic.hospital_id"
            +" ) xx  "
            +" WHERE vaexamtime BETWEEN  DATE_SUB(CURDATE(),INTERVAL 3 YEAR) AND CURDATE()"
            +" GROUP BY stat_dt,county"
        }
    }
module.exports = sql;

